In [1]:
# başlamak için verisetini indiriyoruz.

!wget https://raw.githubusercontent.com/eonurk/eksiGPT/c03b0394808b724a89f519ba9457f0bc623bbc23/data/eksi_articles.txt

--2024-12-07 22:15:02--  https://raw.githubusercontent.com/eonurk/eksiGPT/c03b0394808b724a89f519ba9457f0bc623bbc23/data/eksi_articles.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3647853 (3.5M) [text/plain]
Saving to: ‘eksi_articles.txt’

eksi_articles.txt   100%[===================>]   3.48M  --.-KB/s    in 0.08s   

2024-12-07 22:15:03 (44.1 MB/s) - ‘eksi_articles.txt’ saved [3647853/3647853]



In [2]:
# hadi veriyi inceleyelim.
with open('eksi_articles.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
# ilk 2000 karaktere bakalım
print(text[:2000])

Title: TARİH
Category: TARİH

Content:
1741 yılında yedi aylık bir deniz yolculuğunun ardından hollandalı kaptan douwemout van der meer, dişi genç bir hint gergedanıyla rotterdam limanına geldi. 1579 yılından bu yana avrupa'ya gelen ilk gergedandı bu!

avrupalılar için gergedan, tek boynuzlu at kadar efsanevi bir varlıktı. o güne dek gerçekten yaşadığına bir çok insanın inanmadığı hayvanın gerçekten var olduğunun tek kanıtı albrecht dürer'in 1515 tarihli gravür baskısıydı.

bayan clara ismi konulan dişi hint gergedanı, 1744'te almanya'nın hamburg kentine ilk gezisini yapmadan önce birkaç yıl boyunca hollanda'da sergilendi . ardından tüm avrupayı gezen gergedan 3 kez de ingiltere'ye götürüldü ( bu seyahatler sırasında onu taşıyamadığı için çöken vagonlar, roma'da olduğu sırada kapalı tutulduğu ağırda sıkılıp boynuzunu ahşap duvarlara sürterek kırması gibi pek çok detayla sizi sıkmayalım).

hayatta olduğu süreçte avrupa'da bir gergedan çılgınlığı başladı. çok sayıda gergedan temalı hediy

In [4]:
print("karakter sayısı: ", len(text))

karakter sayısı:  3359477


In [5]:
karakter = sorted(set(text))
sozluk_buyuklugu = len(karakter)
print("karakter sayısı: ", sozluk_buyuklugu)
print("".join(karakter))

karakter sayısı:  135

 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz| £¯°´ÇÖ×ÜàáâäçèéêëíîñóôöúûüĞğİıŞşš–—‘’“”•…€


In [6]:
# karakterleri sayılara çevirelim
ceviri = { ch:i for i,ch in enumerate(karakter) }
irivec = { i:ch for i,ch in enumerate(karakter) }

encode = lambda s: [ceviri[c] for c in s] # encoder: bi kelimeyi sayiya cevirir
decode = lambda l: ''.join([irivec[i] for i in l]) # decode: sayiyi kelimeye cevirir


girdi = "onur bu video olmadi"
cikti = encode(girdi)

print(cikti)
print(decode(cikti))

[79, 78, 85, 82, 1, 66, 85, 1, 86, 73, 68, 69, 79, 1, 79, 76, 77, 65, 68, 73]
onur bu video olmadi


In [7]:
import torch

data = torch.tensor(encode(text), dtype=torch.long)

print(data.shape, data.dtype)
print(data[:1000])

torch.Size([3359477]) torch.int64
tensor([ 53,  73,  84,  76,  69,  27,   1,  53,  34,  51, 121,  41,   0,  36,
         65,  84,  69,  71,  79,  82,  89,  27,   1,  53,  34,  51, 121,  41,
          0,   0,  36,  79,  78,  84,  69,  78,  84,  27,   0,  18,  24,  21,
         18,   1,  89, 122,  76, 122,  78,  68,  65,   1,  89,  69,  68,  73,
          1,  65,  89,  76, 122,  75,   1,  66,  73,  82,   1,  68,  69,  78,
         73,  90,   1,  89,  79,  76,  67,  85,  76,  85, 120,  85,  78,  85,
         78,   1,  65,  82,  68, 122,  78,  68,  65,  78,   1,  72,  79,  76,
         76,  65,  78,  68,  65,  76, 122,   1,  75,  65,  80,  84,  65,  78,
          1,  68,  79,  85,  87,  69,  77,  79,  85,  84,   1,  86,  65,  78,
          1,  68,  69,  82,   1,  77,  69,  69,  82,  13,   1,  68,  73, 124,
         73,   1,  71,  69,  78, 105,   1,  66,  73,  82,   1,  72,  73,  78,
         84,   1,  71,  69,  82,  71,  69,  68,  65,  78, 122,  89,  76,  65,
          1,  82,  79,  84,  8

In [8]:
n = int(0.9*len(data))
print(n)

egitim = data[:n]
test = data[n:]

3023529


In [9]:
pencere = 8

decode(egitim[:pencere].tolist())

'Title: T'

In [10]:
# next token prediction : sonraki heceyi tahmin

x = egitim[:pencere]
y = egitim[1:pencere+1]

for t in range(pencere):
    girdi = x[:t+1]
    cikti = y[t]
    print(f"girdi: {girdi} cikti: {cikti}")

girdi: tensor([53]) cikti: 73
girdi: tensor([53, 73]) cikti: 84
girdi: tensor([53, 73, 84]) cikti: 76
girdi: tensor([53, 73, 84, 76]) cikti: 69
girdi: tensor([53, 73, 84, 76, 69]) cikti: 27
girdi: tensor([53, 73, 84, 76, 69, 27]) cikti: 1
girdi: tensor([53, 73, 84, 76, 69, 27,  1]) cikti: 53
girdi: tensor([53, 73, 84, 76, 69, 27,  1, 53]) cikti: 34


In [11]:
irivec[30]

'='

In [12]:
torch.randint(len(data) - pencere, (135,))

tensor([1546264,  797554, 1705949,  485052, 2270829, 1203360, 2129173, 2947139,
        1085689,  538805,  151156,  435356, 3258120, 2522716,  589448, 2542052,
         115261,  242714, 1890832, 1328730, 2565749, 2295007, 2287857, 2303089,
        3289217, 1754582, 2827161, 2343760,  334723, 2123318, 2352865, 1204149,
        2069483,  276749,  456082,  592483, 2413798, 1574681, 2147049,  487989,
         735639,  877637, 2493379, 2739212,  707954, 3089008,  417337, 1615266,
         499017, 2254779, 2408388, 2262355, 1545691, 3217532, 3161126,  485672,
        1194125, 2146393, 1494360,  737353,   62959, 1101906, 1444246, 3154669,
        2499099, 2410634, 1213848, 1610670,   64055, 1842803, 3040945, 3281521,
        2516767, 2092095, 1928027, 2294466,  802081,  278608, 3109042,   26537,
        2646022, 2189404, 1673078, 1459536, 3150110, 1914237, 1163819, 1191150,
        2298397, 1744189, 2052307, 1644274, 1187758,  509778, 2780471,  723546,
         813747, 2880414, 1048853, 12187

In [13]:
kume = 4 # batch (B)
pencere = 8 # context window (T)


def get_batch(split, kume = 4):
    # generate a small batch of data of inputs x and targets y
    data = egitim if split == 'egitim' else test
    ix = torch.randint(len(data) - pencere, (kume,))
    x = torch.stack([data[i:i+pencere] for i in ix])
    y = torch.stack([data[i+1:i+pencere+1] for i in ix])
    return x, y


xb, yb = get_batch('egitim')
print('girdi:')
print(xb.shape)
print(xb)
print('cikti:')
print(yb.shape)
print(yb)

print('----')

for b in range(kume):
    for t in range(pencere):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"girdi {context.tolist()} cikti: {target}")

girdi:
torch.Size([4, 8])
tensor([[80, 76, 79, 84, 76, 73, 66,  1],
        [90, 65, 77, 65, 78,  1, 71, 69],
        [68, 65, 13,  1, 75, 65, 82, 73],
        [32,  1, 65, 77, 69, 82, 73, 75]])
cikti:
torch.Size([4, 8])
tensor([[ 76,  79,  84,  76,  73,  66,   1,  75],
        [ 65,  77,  65,  78,   1,  71,  69, 105],
        [ 65,  13,   1,  75,  65,  82,  73,  89],
        [  1,  65,  77,  69,  82,  73,  75,  65]])
----
girdi [80] cikti: 76
girdi [80, 76] cikti: 79
girdi [80, 76, 79] cikti: 84
girdi [80, 76, 79, 84] cikti: 76
girdi [80, 76, 79, 84, 76] cikti: 73
girdi [80, 76, 79, 84, 76, 73] cikti: 66
girdi [80, 76, 79, 84, 76, 73, 66] cikti: 1
girdi [80, 76, 79, 84, 76, 73, 66, 1] cikti: 75
girdi [90] cikti: 65
girdi [90, 65] cikti: 77
girdi [90, 65, 77] cikti: 65
girdi [90, 65, 77, 65] cikti: 78
girdi [90, 65, 77, 65, 78] cikti: 1
girdi [90, 65, 77, 65, 78, 1] cikti: 71
girdi [90, 65, 77, 65, 78, 1, 71] cikti: 69
girdi [90, 65, 77, 65, 78, 1, 71, 69] cikti: 105
girdi [68] cikti: 

In [14]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1500)


class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # basit bir tablo (icerisinde olasiliklar var)
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, hedef=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if hedef is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            hedef = hedef.view(B*T)

            loss = F.cross_entropy(logits, hedef)

        return logits, loss

    def tahmin(self, idx, max_karakter):

        for _ in range(max_karakter):

            logits, loss = self(idx)

            # sonuncu zamana odaklan
            logits = logits[:, -1, :] # becomes (B, C)
            # olasiliklari her bir kume icin normalize ediyoruz
            probs = F.softmax(logits, dim=-1) # (B, C)
            # yeni bir karakter seciyoruz
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # sona ekle
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)

        return idx

m = BigramLanguageModel(sozluk_buyuklugu)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

torch.Size([32, 135])
tensor(5.7664, grad_fn=<NllLossBackward0>)


In [15]:
# ornekleme
torch.multinomial(torch.tensor([0.1,0.1, 0.1, 0.1, 0.8]), num_samples=1)

tensor([0])

In [16]:
print(decode(m.tahmin(idx = torch.zeros((1, 1), dtype=torch.long), max_karakter=100)[0].tolist()))


@z.qcs3éê’Ml m[ +Zé2]ücEYrîóYê£e“,°$J|^ı'šFa–Çsc=#èufêâ'¯bZTxA/d×ûBcEMjó•OñTLşRq=U,THÇ[AWRG¯zLë…ó#tV


In [17]:
# optimizer objesi olusturduk
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [18]:
kume = 32
for adim in range(10000):

    # sample a batch of data
    xb, yb = get_batch('egitim', kume=kume)

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.6282131671905518


In [19]:
idx = torch.ones((1, 1), dtype=torch.long)

print(decode(m.tahmin(idx, max_karakter=100)[0].tolist()))

 1
an gömadaakomerın selakendeó“aleğerın böntle be jLbiçlın 1, ha dasey epiyi padomeclekürajahtenek b


In [20]:
8000000000//(135*135)

438957

https://github.com/eonurk/eksiGPT

Burada ilk videoyu bitirdik! Peki neler ogrendik?

* Dokümanların içerisindeki karakter sayısı boyutunu belirliyor. Bizim dokümanda 3.5 milyon karakter var yani yaklaşık 3.5 Megabyte.

* Next token prediction, yani sonraki hece tahmini en önemli fikirlerden biri. Çünkü neyi tahmin etmemiz gerektiğini artık biliyoruz.

* Normalde heceleri de tahmin edebiliriz ama biz şu anda karakterleri tahmin ediyoruz ve bunları teker teker yapıyoruz. Yani bir önceki harf diğerini takip ediyor. Buna literatürde bigram model deniliyor.
Matematiksel olarak da şöyle:$$P(c_i​∣c_1​,c_2​,…,c_{i−1​})≈P(c_i​∣c_{i−1}​)$$ yani, bir dökümandaki i sıradaki karakteri tahmin etmek için normalde ondan önceki tüm karakterleri bilmemiz gerekir ama burada sadece i-1 inci karakteri (yani tahmin edilenden sadece bir önceki) bilmenin tüm karakterleri bilmeye eşit olduğunu varsayıyoruz. Tabi bu bi noktaya kadar doğru ve çok da iyi bir model değil! Örneğin 'anen göteğ' tahmin etmesi gibi :D

PART 2: **DIKKAT!** (**ATTENTION!**)

In [21]:
# https://arxiv.org/pdf/1706.03762 (Transformer makalesi)

import torch
torch.manual_seed(1337)

B,T,C = 4,8,2 # kume, pencere, kanal (simdilik 2, normalde 135)
x = torch.randn(B,T,C).float()
x.shape

torch.Size([4, 8, 2])

In [22]:
# ornek endeksleme (indexing)

print(x[0]) # (, T, C) = (T,C) = (8,2)
# print("\n")
# print(x[0, 0]) # (, , C) = (C) = (2)
# print("\n")
# print(x[:, 1, 1]) # (B, , ) = (B) = (4)

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])


In [23]:
x_ortalama = torch.zeros((B,T,C))

for b in range(B):
    for t in range(T):

        onceki_x = x[b, :t+1] # (, t, C) = (t, C)

        # zaman boyutunda o zamana kadarki ortalamalari (C)
        x_ortalama[b,t] = torch.mean(onceki_x, dim=0)

In [24]:
x[0]

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])

In [25]:
x_ortalama[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [26]:
# hadi sağlama yapalım! :D
print((0.1808 - 0.3596) /2)
print((0.1808 - 0.3596 + 0.6258) /3)

-0.0894
0.14900000000000002


In [27]:
# MATRIS MATEMATIGINE HOSGELDINIZ!
torch.manual_seed(1337)

a = torch.tril(torch.ones(3,3))
a = a / torch.sum(a, 1, keepdim=True)

b = torch.randint(0,10,(3,3)).float()
c = a @ b # kartezyen carpma islemi

print("a:\n", a)
print("\n=======================\n")
print("b:\n", b)
print("\n=======================\n")
print("c:\n", c)

a:
 tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])


b:
 tensor([[5., 7., 2.],
        [0., 5., 3.],
        [5., 0., 4.]])


c:
 tensor([[5.0000, 7.0000, 2.0000],
        [2.5000, 6.0000, 2.5000],
        [3.3333, 4.0000, 3.0000]])


In [28]:
# hadi saglama yapalim x2! :D
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
wei

x_ortalama_2 = wei @ x # (, T, T) @ (B, T, C) = (B, T, C)

print(x_ortalama[3])
print("\n=======================\n")
print(x_ortalama_2[3])

tensor([[ 1.6455, -0.8030],
        [ 1.4985, -0.5395],
        [ 0.4954,  0.3420],
        [ 1.0623, -0.1802],
        [ 1.1401, -0.4462],
        [ 1.0870, -0.4071],
        [ 1.0430, -0.1299],
        [ 1.1138, -0.1641]])


tensor([[ 1.6455, -0.8030],
        [ 1.4985, -0.5395],
        [ 0.4954,  0.3420],
        [ 1.0623, -0.1802],
        [ 1.1401, -0.4462],
        [ 1.0870, -0.4071],
        [ 1.0430, -0.1299],
        [ 1.1138, -0.1641]])


In [29]:
# Aynisini bir daha yapiyoruz bu sefer softmax ile!
tril = torch.tril(torch.ones(T,T))

wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

x_ortalama_3 = wei @ x

print(x_ortalama_2[0])
print("\n=======================\n")
print(x_ortalama_3[0])

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])


tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])


In [30]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# CLIMAX!
# Attention - Dikkat!
# https://arxiv.org/pdf/1706.03762

# tek basli dikkat
torch.manual_seed(1337)

tril = torch.tril(torch.ones(T,T))

dikkat_buyuklugu = 4 # (H)

# 2 tane giris 4 tane cikis
anahtar = nn.Linear(C, dikkat_buyuklugu, bias = False) # (C, H)
sorgu   = nn.Linear(C, dikkat_buyuklugu, bias = False) # (C, H)

# > | >
#   | >
# > | >
#   | >

k = anahtar(x) # key (B,T,H)
q = sorgu(x) # query (B,T,H)

wei = k @ q.transpose(-2, -1) * dikkat_buyuklugu ** -0.5 # (B, T, H) @ (B, H, T) -> (B, T, T)

print(wei.var())
# wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

print(wei[0]) # (T,T)

cikti = wei @ x # (B, T, T) @ (B, T, C) = (B, T, C)

tensor(0.2593, grad_fn=<VarBackward0>)
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4853, 0.5147, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3345, 0.2980, 0.3675, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2333, 0.1957, 0.2701, 0.3009, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1878, 0.1774, 0.2230, 0.2549, 0.1568, 0.0000, 0.0000, 0.0000],
        [0.1421, 0.1816, 0.1107, 0.0918, 0.1413, 0.3325, 0.0000, 0.0000],
        [0.1429, 0.1366, 0.1444, 0.1452, 0.1516, 0.1373, 0.1419, 0.0000],
        [0.1324, 0.1590, 0.1354, 0.1389, 0.0945, 0.1265, 0.1399, 0.0734]],
       grad_fn=<SelectBackward0>)


In [31]:
k = torch.randn(B,T,dikkat_buyuklugu)
q = torch.randn(B,T,dikkat_buyuklugu)

wei = q @ k.transpose(-2, -1)

print(wei.var())

wei = wei * dikkat_buyuklugu ** -0.5

print("\n", wei.var())

tensor(4.5029)

 tensor(1.1257)
