In [1]:
# başlamak için verisetini indiriyoruz.

!wget https://raw.githubusercontent.com/eonurk/eksiGPT/c03b0394808b724a89f519ba9457f0bc623bbc23/data/eksi_articles.txt

--2024-12-04 08:10:07--  https://raw.githubusercontent.com/eonurk/eksiGPT/c03b0394808b724a89f519ba9457f0bc623bbc23/data/eksi_articles.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3647853 (3.5M) [text/plain]
Saving to: ‘eksi_articles.txt’

eksi_articles.txt   100%[===================>]   3.48M  --.-KB/s    in 0.09s   

2024-12-04 08:10:08 (40.7 MB/s) - ‘eksi_articles.txt’ saved [3647853/3647853]



In [2]:
# hadi veriyi inceleyelim.
with open('eksi_articles.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [4]:
# ilk 2000 karaktere bakalım
print(text[:2000])

Title: TARİH
Category: TARİH

Content:
1741 yılında yedi aylık bir deniz yolculuğunun ardından hollandalı kaptan douwemout van der meer, dişi genç bir hint gergedanıyla rotterdam limanına geldi. 1579 yılından bu yana avrupa'ya gelen ilk gergedandı bu!

avrupalılar için gergedan, tek boynuzlu at kadar efsanevi bir varlıktı. o güne dek gerçekten yaşadığına bir çok insanın inanmadığı hayvanın gerçekten var olduğunun tek kanıtı albrecht dürer'in 1515 tarihli gravür baskısıydı.

bayan clara ismi konulan dişi hint gergedanı, 1744'te almanya'nın hamburg kentine ilk gezisini yapmadan önce birkaç yıl boyunca hollanda'da sergilendi . ardından tüm avrupayı gezen gergedan 3 kez de ingiltere'ye götürüldü ( bu seyahatler sırasında onu taşıyamadığı için çöken vagonlar, roma'da olduğu sırada kapalı tutulduğu ağırda sıkılıp boynuzunu ahşap duvarlara sürterek kırması gibi pek çok detayla sizi sıkmayalım).

hayatta olduğu süreçte avrupa'da bir gergedan çılgınlığı başladı. çok sayıda gergedan temalı hediy

In [5]:
print("karakter sayısı: ", len(text))

karakter sayısı:  3359477


In [8]:
karakter = sorted(set(text))
sozluk_buyuklugu = len(karakter)
print("karakter sayısı: ", sozluk_buyuklugu)
print("".join(karakter))

karakter sayısı:  135

 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz| £¯°´ÇÖ×ÜàáâäçèéêëíîñóôöúûüĞğİıŞşš–—‘’“”•…€


In [13]:
# karakterleri sayılara çevirelim
ceviri = { ch:i for i,ch in enumerate(karakter) }
irivec = { i:ch for i,ch in enumerate(karakter) }

encode = lambda s: [ceviri[c] for c in s] # encoder: bi kelimeyi sayiya cevirir
decode = lambda l: ''.join([irivec[i] for i in l]) # decode: sayiyi kelimeye cevirir


girdi = "onur bu video olmadi"
cikti = encode(girdi)

print(cikti)
print(decode(cikti))

[79, 78, 85, 82, 1, 66, 85, 1, 86, 73, 68, 69, 79, 1, 79, 76, 77, 65, 68, 73]
onur bu video olmadi


In [15]:
import torch

data = torch.tensor(encode(text), dtype=torch.long)

print(data.shape, data.dtype)
print(data[:1000])

torch.Size([3359477]) torch.int64
tensor([ 53,  73,  84,  76,  69,  27,   1,  53,  34,  51, 121,  41,   0,  36,
         65,  84,  69,  71,  79,  82,  89,  27,   1,  53,  34,  51, 121,  41,
          0,   0,  36,  79,  78,  84,  69,  78,  84,  27,   0,  18,  24,  21,
         18,   1,  89, 122,  76, 122,  78,  68,  65,   1,  89,  69,  68,  73,
          1,  65,  89,  76, 122,  75,   1,  66,  73,  82,   1,  68,  69,  78,
         73,  90,   1,  89,  79,  76,  67,  85,  76,  85, 120,  85,  78,  85,
         78,   1,  65,  82,  68, 122,  78,  68,  65,  78,   1,  72,  79,  76,
         76,  65,  78,  68,  65,  76, 122,   1,  75,  65,  80,  84,  65,  78,
          1,  68,  79,  85,  87,  69,  77,  79,  85,  84,   1,  86,  65,  78,
          1,  68,  69,  82,   1,  77,  69,  69,  82,  13,   1,  68,  73, 124,
         73,   1,  71,  69,  78, 105,   1,  66,  73,  82,   1,  72,  73,  78,
         84,   1,  71,  69,  82,  71,  69,  68,  65,  78, 122,  89,  76,  65,
          1,  82,  79,  84,  8

In [19]:
n = int(0.9*len(data))
print(n)

egitim = data[:n]
test = data[n:]

3023529


In [22]:
pencere = 8

decode(egitim[:pencere].tolist())

'Title: T'

In [23]:
# next token prediction : sonraki heceyi tahmin

x = egitim[:pencere]
y = egitim[1:pencere+1]

for t in range(pencere):
    girdi = x[:t+1]
    cikti = y[t]
    print(f"girdi: {girdi} cikti: {cikti}")

girdi: tensor([53]) cikti: 73
girdi: tensor([53, 73]) cikti: 84
girdi: tensor([53, 73, 84]) cikti: 76
girdi: tensor([53, 73, 84, 76]) cikti: 69
girdi: tensor([53, 73, 84, 76, 69]) cikti: 27
girdi: tensor([53, 73, 84, 76, 69, 27]) cikti: 1
girdi: tensor([53, 73, 84, 76, 69, 27,  1]) cikti: 53
girdi: tensor([53, 73, 84, 76, 69, 27,  1, 53]) cikti: 34


In [27]:
irivec[30]

'='

In [56]:
torch.randint(len(data) - pencere, (135,))

tensor([3214428, 2261923, 2916989, 2648489, 1515006, 2496588, 1897310, 2360446,
        1957980, 2212464, 3084998, 2117740,  908837, 2226090, 3119378, 1208542,
         122816, 2242072,  997824,  900568,  552365, 1649054, 1027382,  718861,
        3294556, 2664511, 2356029, 1221639, 2863303,  970164, 1645838,  693960,
         163146,  522755, 2783753, 1109376,  324824,  431674, 1061113, 1748629,
        3289727,  363804,  728752, 3241168, 1848855,  823231, 2159091, 2121684,
        2689751, 3291177, 2596121,  563877, 2439666, 2228511, 2364621, 3047075,
        1860791, 1844327, 1422337, 1226523,  318987,  702426, 2587319, 3305310,
        3201177,  843756, 1573154, 1115801, 2215372,  631584,  250812,   52344,
        1322408, 1328144, 2743445, 2591878, 3072138, 1386819,  386053, 2014961,
        3137669, 1446794, 1254294, 2663590, 1811119, 2647290, 1042172,  587076,
        2564797, 3251997,  922660, 2496522,  843381, 1403777, 1457655,  206804,
        2152099, 2416365, 2456420, 17864

In [146]:
kume = 4 # batch (B)
pencere = 8 # context window (T)


def get_batch(split, kume = 4):
    # generate a small batch of data of inputs x and targets y
    data = egitim if split == 'egitim' else test
    ix = torch.randint(len(data) - pencere, (kume,))
    x = torch.stack([data[i:i+pencere] for i in ix])
    y = torch.stack([data[i+1:i+pencere+1] for i in ix])
    return x, y


xb, yb = get_batch('egitim')
print('girdi:')
print(xb.shape)
print(xb)
print('cikti:')
print(yb.shape)
print(yb)

print('----')

for b in range(kume):
    for t in range(pencere):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"girdi {context.tolist()} cikti: {target}")

girdi:
torch.Size([4, 8])
tensor([[ 77,  69,  89,  69,   1,  71,  69,  82],
        [ 78,  65,  83,  82,  65,  76,  76,  65],
        [  1,  65,  82,  65,  66,  65,  76,  65],
        [ 20,  15,   1,  77, 115,   1,  21,  23]])
cikti:
torch.Size([4, 8])
tensor([[ 69,  89,  69,   1,  71,  69,  82,  69],
        [ 65,  83,  82,  65,  76,  76,  65,  72],
        [ 65,  82,  65,  66,  65,  76,  65,  82],
        [ 15,   1,  77, 115,   1,  21,  23,   1]])
----
girdi [77] cikti: 69
girdi [77, 69] cikti: 89
girdi [77, 69, 89] cikti: 69
girdi [77, 69, 89, 69] cikti: 1
girdi [77, 69, 89, 69, 1] cikti: 71
girdi [77, 69, 89, 69, 1, 71] cikti: 69
girdi [77, 69, 89, 69, 1, 71, 69] cikti: 82
girdi [77, 69, 89, 69, 1, 71, 69, 82] cikti: 69
girdi [78] cikti: 65
girdi [78, 65] cikti: 83
girdi [78, 65, 83] cikti: 82
girdi [78, 65, 83, 82] cikti: 65
girdi [78, 65, 83, 82, 65] cikti: 76
girdi [78, 65, 83, 82, 65, 76] cikti: 76
girdi [78, 65, 83, 82, 65, 76, 76] cikti: 65
girdi [78, 65, 83, 82, 65, 76, 76, 

In [138]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1500)


class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # basit bir tablo (icerisinde olasiliklar var)
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, hedef=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if hedef is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            hedef = hedef.view(B*T)

            loss = F.cross_entropy(logits, hedef)

        return logits, loss

    def tahmin(self, idx, max_karakter):

        for _ in range(max_karakter):

            logits, loss = self(idx)

            # sonuncu zamana odaklan
            logits = logits[:, -1, :] # becomes (B, C)
            # olasiliklari her bir kume icin normalize ediyoruz
            probs = F.softmax(logits, dim=-1) # (B, C)
            # yeni bir karakter seciyoruz
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # sona ekle
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)

        return idx

m = BigramLanguageModel(sozluk_buyuklugu)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

torch.Size([32, 135])
tensor(5.2559, grad_fn=<NllLossBackward0>)


In [119]:
# ornekleme
torch.multinomial(torch.tensor([0.1,0.1, 0.1, 0.1, 0.8]), num_samples=1)

tensor([4])

In [139]:
print(decode(m.tahmin(idx = torch.zeros((1, 1), dtype=torch.long), max_karakter=100)[0].tolist()))


HYz.qcs3éê’Ml m[ +Zé2]ücEYrîóYê£e“,°$J|^ı'šFa–Çsc=#èufêâ'¯bZTxA/d×ûBcEMjó•OñTLşRq=U,THÇ[AWRG¯zLë…ó#t


In [140]:
# optimizer objesi olusturduk
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [155]:
kume = 64
for adim in range(1000):

    # sample a batch of data
    xb, yb = get_batch('egitim', kume=kume)

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.5028345584869385


In [162]:
idx = torch.ones((1, 1), dtype=torch.long)

print(decode(m.tahmin(idx, max_karakter=100)[0].tolist()))

 |-leni dedasüşı i ezır ön argöyrndeG”ızam, vi lktı ertüverstise kabu201.

Caywmardoldene dakemı bins


In [167]:
8000000000//(135*135)

438957

https://github.com/eonurk/eksiGPT